In [1]:
import numpy as np

In [3]:
#Készíts egy függvényt ami létre hoz egy nullákkal teli numpy array-t.
#Paraméterei: mérete (tupel-ként), default mérete pedig legyen egy (2,2)
#Be: (2,2)
#Ki: [[0,0],[0,0]]
#create_array()

In [11]:
def create_array(size: tuple = (2,2)) -> np.array:
    return np.zeros(size)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#Készíts egy függvényt ami a paraméterként kapott array-t főátlót feltölti egyesekkel
#Be: [[1,2],[3,4]]
#Ki: [[1,2],[3,1]]
#set_one()

In [29]:
def set_one(input_array: np.array)-> np.array:
    np.fill_diagonal(input_array,1)
    return input_array


[[1 0]
 [0 1]]


In [ ]:
# Transzponáld a paraméterül kapott mártix-ot:
# Be: [[1, 2], [3, 4]]
# Ki: [[1, 2], [3, 4]]
# do_transpose()

In [33]:
def do_transpose(input_array: np.array)->np.array:
    return np.transpose(input_array)


array([[1, 3],
       [2, 4]])

In [ ]:
# Készíts egy olyan függvényt ami az array-ben lévő értékeket N tizenedjegyik kerekíti, alapértelmezetten 
# Be: [0.1223, 0.1675], n = 2
# Ki: [0.12, 0.17]
# round_array()

In [35]:
def round_array(input_array: np.array, n: int)->np.array:
    return np.around(input_array, n)

array([0.12, 0.17])

In [37]:
# Készíts egy olyan függvényt, ami a bementként  0 és 1 ből álló tömben a 0 - False-ra az 1 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# bool_array()

In [51]:
def bool_array(input_array: np.array)->np.array:
    return input_array.astype(bool)

In [ ]:
# Készíts egy olyan függvényt, ami a bementként  0 és 1 ből álló tömben a 1 - False-ra az 0 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# invert_bool_array()

In [56]:
def invert_bool_array(input_array: np.array)-> np.array:
    return np.invert(input_array.astype(bool))

In [ ]:
# Készíts egy olyan függvényt ami a paraméterként kapott array-t kilapítja
# Be: [[1,2], [3,4]]
# Ki: [1,2,3,4]
# flatten()

In [58]:
def flatten(input_array: np.array)->np.array:
    return np.ndarray.flatten(input_array)

array([1, 2, 3, 4])